/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceListing = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'clientName' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const RecoveryRequest = IDL.Record({
  'status' : RequestStatus,
  'serviceTier' : IDL.Text,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'walletType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const RequestSubmission = IDL.Record({
  'serviceTier' : IDL.Text,
  'name' : IDL.Text,
  'walletType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addServiceListing' : IDL.Func([ServiceListing], [IDL.Nat], []),
  'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRequests' : IDL.Func([], [IDL.Vec(RecoveryRequest)], ['query']),
  'getAllServiceListings' : IDL.Func([], [IDL.Vec(ServiceListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTopTestimonials' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(Testimonial))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRequests' : IDL.Func([], [IDL.Vec(RecoveryRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func([RequestSubmission], [IDL.Nat], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceListing = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'clientName' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const RecoveryRequest = IDL.Record({
    'status' : RequestStatus,
    'serviceTier' : IDL.Text,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'walletType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const RequestSubmission = IDL.Record({
    'serviceTier' : IDL.Text,
    'name' : IDL.Text,
    'walletType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addServiceListing' : IDL.Func([ServiceListing], [IDL.Nat], []),
    'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRequests' : IDL.Func([], [IDL.Vec(RecoveryRequest)], ['query']),
    'getAllServiceListings' : IDL.Func(
        [],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTopTestimonials' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(Testimonial))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRequests' : IDL.Func([], [IDL.Vec(RecoveryRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func([RequestSubmission], [IDL.Nat], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };