/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RecoveryRequest {
  'status' : RequestStatus,
  'serviceTier' : string,
  'name' : string,
  'user' : Principal,
  'walletType' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type RequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface RequestSubmission {
  'serviceTier' : string,
  'name' : string,
  'walletType' : string,
  'email' : string,
  'message' : string,
}
export interface ServiceListing {
  'name' : string,
  'description' : string,
  'currency' : string,
  'price' : bigint,
}
export interface Testimonial {
  'clientName' : string,
  'message' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addServiceListing' : ActorMethod<[ServiceListing], bigint>,
  'addTestimonial' : ActorMethod<[Testimonial], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRequests' : ActorMethod<[], Array<RecoveryRequest>>,
  'getAllServiceListings' : ActorMethod<[], Array<ServiceListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTopTestimonials' : ActorMethod<[], [] | [Array<Testimonial>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRequests' : ActorMethod<[], Array<RecoveryRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRequest' : ActorMethod<[RequestSubmission], bigint>,
  'updateRequestStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];